require './lib/helpers/gkelite/gk_header'


class GKShopifyBasePage < BasePage
	include PageObject
	include GKHeader

	text_field(:password, id: "password")
	button(:enter, name: "commit")

	def get_spo_product_handles
		@handles = Array.new
		options = AssetAPI.scene_productoptions_keys('gk-prs-gym')
		options.flatten
		options.each do |opts|
			@handles.push(opts)
		end
		@handles.uniq!
		@handles.reject! { |r| r.include?("extra" || "mannequin" || "scene.json" || "dummy") }
		@handles.flatten!
	end


	def enter_password
		self.password_element.send_keys "iawhao"
		self.enter_element.click
	end


	def login_page
		$driver.goto $base_url + "/account/login"
		return GKLoginPage.new
	end

	def cart_page
		$driver.goto $base_url + "/cart"
		return GKCartPage.new
	end

	def search_page
		$driver.goto $base_url + "/pages/search-results-page?q="
		return GKSearchPage.new
	end

	def product_page(id)
		$driver.goto $base_url + "/products/#{id}"
		return GKProductPage.new
	end

	def home_page
		$driver.goto $base_url
		return GKHomePage.new
	end

	def collections(id)
		$driver.goto $base_url + "/collections/#{id}?view=product"
	end

	$gk_palette_colors = {
		"gk-slg-holo-palette" => [
			"gk-sel-holo-49b-red-prism-color",
			"gk-sel-holo-u74-grape-opalescence-color",
			"gk-sel-holo-l35-black-sparkle-color",
			"gk-sel-holo-799-white-sparkle-color",
			"gk-sel-holo-j63-kelly-sparkle-color",
			"gk-sel-holo-p28-radiantroyal-sparkle-color",
			"gk-sel-holo-u06-fiesta-opalescence-color",
			"gk-sel-holo-u07-jet-opalescence-color",
			"gk-sel-holo-u08-fiesta-sparkle-color",
			"gk-sel-holo-u71-magenta-sparkle-color",
			"gk-sel-holo-u72-gold-opalescence-color",
			"gk-sel-holo-u75-berry-opalescence-color",
			"gk-sel-holo-u76-neongreen-opalescence-color",
			"gk-sel-holo-u77-seaglass-opalescence-color",
			"gk-sel-holo-u80-neonyellow-opalescence-color",
			"gk-sel-holo-v02-white-opalescence-color",
			"gk-sel-holo-v84-lemonlime-sparkle-color",
			"gk-sel-holo-w64-turquoise-opalescence-color",
			"gk-sel-holo-w65-magenta-opalescence-color",
			"gk-sel-holo-w72-imperialpurple-sparkle-color",
			"gk-sel-holo-w73-pacific-opalescence-color",
			"gk-sel-holo-a75-seaglass-sparkle-color",
			"gk-sel-holo-h36-turquoise-sparkle-color",
			"gk-sel-holo-p27-wild-sangria-sparkle-color",
			"gk-sel-holo-p13-azure-sparkle-color",
			"gk-sel-holo-23a-imperialpurple-opalescence-color"],

			"gk-slg-nylpf-palette" => [
				"gk-sel-nylspanfoil-f24-gold-mystique-color",
				"gk-sel-nylspanfoil-752-columbiablue-mystique-color",
				"gk-sel-nylspanfoil-902-ocean-mystique-color",
				"gk-sel-nylspanfoil-24a-wildorchid-mystique-color",
				"gk-sel-nylspanfoil-b81-red-mystique-color",
				"gk-sel-nylspanfoil-d07-sunshine-mystique-color",
				"gk-sel-nylspanfoil-d16-grape-mystique-color",
				"gk-sel-nylspanfoil-d17-cherry-mystique-color",
				"gk-sel-nylspanfoil-e16-navy-mystique-color",
				"gk-sel-nylspanfoil-e59-blueraspberry-mystique-color",
				"gk-sel-nylspanfoil-e84-silver-mystique-color",
				"gk-sel-nylspanfoil-f21-berry-mystique-color",
				"gk-sel-nylspanfoil-f22-black-mystique-color",
				"gk-sel-nylspanfoil-f23-rainforest-mystique-color",
				"gk-sel-nylspanfoil-f26-white-mystique-color",
				"gk-sel-nylspanfoil-f87-electricturquoise-mystique-color",
				"gk-sel-nylspanfoil-g83-lemonlime-mystique-color",
				"gk-sel-nylspanfoil-h57-evergreen-mystique-color",
				"gk-sel-nylspanfoil-h58-vinca-mystique-color",
				"gk-sel-nylspanfoil-h63-lavenderice-mystique-color",
				"gk-sel-nylspanfoil-h81-richroyal-mystique-color",
				"gk-sel-nylspanfoil-j09-mintjulep-mystique-color",
				"gk-sel-nylspanfoil-j46-plum-mystique-color",
				"gk-sel-nylspanfoil-k91-lime-mystique-color",
				"gk-sel-nylspanfoil-l23-gunmetal-mystique-color",
				"gk-sel-nylspanfoil-l29-steel-mystique-color",
				"gk-sel-nylspanfoil-l31-azure-mystique-color",
				"gk-sel-nylspanfoil-l72-yellow-mystique-color",
				"gk-sel-nylspanfoil-l93-charcoal-mystique-color",
				"gk-sel-nylspanfoil-m37-merlot-mystique-color",
				"gk-sel-nylspanfoil-n98-kellygreen-mystique-color",
				"gk-sel-nylspanfoil-p30-sangria-mystique-color",
				"gk-sel-nylspanfoil-q18-imperialpurple-mystique-color",
				"gk-sel-nylspanfoil-u73-neonyellow-mystique-color",
				"gk-sel-nylspanfoil-v04-passion-mystique-color",
				"gk-sel-nylspanfoil-v05-sterlingsilver-mystique-color",
				"gk-sel-nylspanfoil-x77-neoncoral-mystique-color",
				"gk-sel-nylspanfoil-25a-peacock-iridescent-color",
				"gk-sel-nylspanfoil-22a-champagne-mystique-color",
				"gk-sel-nylspanfoil-51a-fluorescentlime-mystique-color",
				"gk-sel-nylspanfoil-52a-fluorescentpink-mystique-color",
				"gk-sel-nylspanfoil-53a-fluorescentorange-mystique-color",
				"gk-sel-nylspanfoil-54a-fluorescentyellow-mystique-color",
				"gk-sel-nylspanfoil-l24-gold-leaf-color"],

				"gk-slg-mesh-palette" => [
					"gk-sel-mesh-027-nude-color",
					"gk-sel-mesh-034-concord-color",
					"gk-sel-mesh-121-ocean-color",
					"gk-sel-mesh-q68-hotred-color",
					"gk-sel-mesh-w28-merlot-color",
					"gk-sel-mesh-024-brown-color",
					"gk-sel-mesh-824-magenta-color",
					"gk-sel-mesh-180-white-color",
					"gk-sel-mesh-015-berry-color",
					"gk-sel-mesh-016-black-color",
					"gk-sel-mesh-g27-calypso-color",
					"gk-sel-mesh-116-navy-color"],

					"gk-slg-embroidery-palette" => [
						"gk-sel-embroidery-180-white-color",
						"gk-sel-embroidery-810-silver-color",
						"gk-sel-embroidery-016-black-color",
						"gk-sel-embroidery-152-red-color",
						"gk-sel-embroidery-124-orange-color",
						"gk-sel-embroidery-068-gold-color",
						"gk-sel-embroidery-069-goldglimmer-color",
						"gk-sel-embroidery-483-yellow-color",
						"gk-sel-embroidery-854-neonyellow-color",
						"gk-sel-embroidery-085-forestgreen-color",
						"gk-sel-embroidery-488-limegreen-color",
						"gk-sel-embroidery-x65-emeraldgreen-color",
						"gk-sel-embroidery-170-teal-color",
						"gk-sel-embroidery-096-lightblue-color",
						"gk-sel-embroidery-175-turquoise-color",
						"gk-sel-embroidery-160-royal-color",
						"gk-sel-embroidery-116-navy-color",
						"gk-sel-embroidery-148-purple-color",
						"gk-sel-embroidery-178-violet-color",
						"gk-sel-embroidery-110-maroon-color",
						"gk-sel-embroidery-128-orchid-color",
						"gk-sel-embroidery-17a-rubyglint-color",
						"gk-sel-embroidery-140-pink-color",
						"gk-sel-embroidery-j81-wildpink-color",
						"gk-sel-embroidery-y07-flamingo-color",
						"gk-sel-embroidery-18a-cheekypink-color"],

						"gk-slg-nylon-spandex-palette" => [
							"gk-sel-nylspan-015-berry-color",
							"gk-sel-nylspan-028-burgundy-color",
							"gk-sel-nylspan-067-evergreen-color",
							"gk-sel-nylspan-068-gold-color",
							"gk-sel-nylspan-088-kellygreen-color",
							"gk-sel-nylspan-116-navy-color",
							"gk-sel-nylspan-124-orange-color",
							"gk-sel-nylspan-139-pewter-color",
							"gk-sel-nylspan-148-purple-color",
							"gk-sel-nylspan-152-red-color",
							"gk-sel-nylspan-160-royal-color",
							"gk-sel-nylspan-165-sapphire-color",
							"gk-sel-nylspan-175-turquoise-color",
							"gk-sel-nylspan-180-white-color",
							"gk-sel-nylspan-192-sangria-color",
							"gk-sel-nylspan-338-electricblue-color",
							"gk-sel-nylspan-824-magenta-color",
							"gk-sel-nylspan-g27-calypso-color",
							"gk-sel-nylspan-v82-lipstick-color",
							"gk-sel-nylspan-v83-wysteria-color",
							"gk-sel-nylspan-016-black-color",
							"gk-sel-nylspan-y06-steel-color"],

							"gk-slg-campus-stretchtek-palette" => [
								"gk-sel-stretchtek-152-red-color",
								"gk-sel-stretchtek-160-royal-color",
								"gk-sel-stretchtek-116-navy-color",
								"gk-sel-stretchtek-180-white-color",
								"gk-sel-stretchtek-016-black-color"],

								"gk-slg-campus-performancemesh-palette" => [
									"gk-sel-performancemesh-152-red-color",
									"gk-sel-performancemesh-160-royal-color",
									"gk-sel-performancemesh-180-white-color",
									"gk-sel-performancemesh-116-navy-color"],

									"gk-slg-techmesh-palette" => [
										"gk-sel-techmesh-116-navy-color",
										"gk-sel-techmesh-152-red-color",
										"gk-sel-techmesh-015-berry-color",
										"gk-sel-techmesh-016-black-color",
										"gk-sel-techmesh-180-white-color",
										"gk-sel-techmesh-n43-neongreen-color",
										"gk-sel-techmesh-041-charcoal-color",
										"gk-sel-techmesh-854-neonyellow-color",
										"gk-sel-techmesh-175-turquoise-color",
										"gk-sel-techmesh-824-magenta-color"],

										"gk-slg-drytech-palette" => [
											"gk-sel-drytech-065-forestgreen-color",
											"gk-sel-drytech-079-graphite-color",
											"gk-sel-drytech-110-maroon-color",
											"gk-sel-drytech-068-gold-color",
											"gk-sel-drytech-c36-columbiablue-color",
											"gk-sel-drytech-n31-carbon-color",
											"gk-sel-drytech-148-purple-color",
											"gk-sel-drytech-124-orange-color",
											"gk-sel-drytech-088-kellygreen-color",
											"gk-sel-drytech-067-evergreen-color",
											"gk-sel-drytech-024-brown-color",
											"gk-sel-drytech-g27-calypso-color",
											"gk-sel-drytech-824-magenta-color",
											"gk-sel-drytech-191-seaglass-color",
											"gk-sel-drytech-016-black-color",
											"gk-sel-drytech-854-neonyellow-color",
											"gk-sel-drytech-116-navy-color",
											"gk-sel-drytech-160-royal-color",
											"gk-sel-drytech-165-sapphire-color",
											"gk-sel-drytech-178-violet-color",
											"gk-sel-drytech-180-white-color",
											"gk-sel-drytech-p47-redhot-color",
											"gk-sel-drytech-015-berry-color",
											"gk-sel-drytech-175-turquoise-color",
											"gk-sel-drytech-483-yellow-color",
											"gk-sel-drytech-w71-truenavy-color",
											"gk-sel-drytech-b57-vegasgold-color",
											"gk-sel-drytech-n43-neongreen-color"],

											"gk-slg-polytek-palette" => [
												"gk-sel-polytek-y22-yellow-color",
												"gk-sel-polytek-y53-neon-yellow-color",
												"gk-sel-polytek-y20-vegas-gold-color",
												"gk-sel-polytek-y54-tangerine-color",
												"gk-sel-polytek-y23-orange-color",
												"gk-sel-polytek-y21-gold-color",
												"gk-sel-polytek-y28-red-color",
												"gk-sel-polytek-y24-coral-color",
												"gk-sel-polytek-y26-candy-apple-color",
												"gk-sel-polytek-y25-cosmo-color",
												"gk-sel-polytek-y29-crimson-color",
												"gk-sel-polytek-y55-neon-pink-color",
												"gk-sel-polytek-y62-hot-pink-color",
												"gk-sel-polytek-y61-berry-color",
												"gk-sel-polytek-y32-cherry-color",
												"gk-sel-polytek-y33-fuchsia-color",
												"gk-sel-polytek-y34-sangria-color",
												"gk-sel-polytek-y31-pink-color",
												"gk-sel-polytek-y63-wildberry-color",
												"gk-sel-polytek-y35-wisteria-color",
												"gk-sel-polytek-y56-ultra-violet-color",
												"gk-sel-polytek-y38-sapphire-color",
												"gk-sel-polytek-y36-purple-color",
												"gk-sel-polytek-y39-midnight-color",
												"gk-sel-polytek-y40-columbia-blue-color",
												"gk-sel-polytek-y57-bright-turquoise-color",
												"gk-sel-polytek-y42-royal-color",
												"gk-sel-polytek-y37-navy-color",
												"gk-sel-polytek-y44-turquoise-color",
												"gk-sel-polytek-y43-electric-blue-color",
												"gk-sel-polytek-y46-evergreen-color",
												"gk-sel-polytek-y45-spruce-color",
												"gk-sel-polytek-y47-kelly-color",
												"gk-sel-polytek-y58-key-lime-color",
												"gk-sel-polytek-y48-gray-color",
												"gk-sel-polytek-y49-flannel-gray-color",
												"gk-sel-polytek-y51-black-color",
												"gk-sel-polytek-y50-carbon-color",
												"gk-sel-polytek-y60-pewter-color",
												"gk-sel-polytek-180-white-color",
												"gk-sel-polytek-y52-brown-color",
												"gk-sel-polytek-y59-aluminum-color",
												"gk-sel-polytek-y03-teal-color",
												"gk-sel-polytek-y04-blue-ribbon-color",
												"gk-sel-polytek-y02-cardinal-color"],

												"gk-slg-crystals-palette" => [
													"gk-sel-crystals-010-clear-color",
													"gk-sel-crystals-001-brilliance-color",
													"gk-sel-crystals-m07-metallicsilver-color",
													"gk-sel-crystals-x64-blackdiamond-color",
													"gk-sel-crystals-016-black-color",
													"gk-sel-crystals-m08-metallicgold-color",
													"gk-sel-crystals-162-ruby-color",
													"gk-sel-crystals-467-tangerine-color",
													"gk-sel-crystals-b66-goldbrilliance-color",
													"gk-sel-crystals-n48-citrine-color",
													"gk-sel-crystals-464-mango-color",
													"gk-sel-crystals-454-kiwi-color",
													"gk-sel-crystals-741-jade-color",
													"gk-sel-crystals-004-aquamarine-color",
													"gk-sel-crystals-338-electricblue-color",
													"gk-sel-crystals-045-cobalt-color",
													"gk-sel-crystals-112-midnight-color",
													"gk-sel-crystals-095-lavender-color",
													"gk-sel-crystals-178-violet-color",
													"gk-sel-crystals-003-amethyst-color",
													"gk-sel-crystals-300-ultraviolet-brilliance-color",
													"gk-sel-crystals-742-fuchsia-color",
													"gk-sel-crystals-192-sangria-color",
													"gk-sel-crystals-140-pink-color",
													"gk-sel-crystals-u09-peacock-brilliance-color",
													"gk-sel-crystals-48a-dark-brilliance-color",
													"gk-sel-crystals-49a-white-pearl-color"],

													"gk-slg-velvet-palette" => [
														"gk-sel-velvet-016-black-color",
														"gk-sel-velvet-165-sapphire-color",
														"gk-sel-velvet-059-eggplant-color"],

														"gk-slg-shadowproof-liner-palette" => [
															"gk-sel-shadowproof-027-nude-color",
															"gk-sel-shadowproof-024-brown-color"],

															"gk-slg-nylon-spandex-ombre-palette"=>[
																"gk-sel-nylspan-ombre-015-berry-color",
																"gk-sel-nylspan-ombre-028-burgundy-color",
																"gk-sel-nylspan-ombre-067-evergreen-color",
																"gk-sel-nylspan-ombre-068-gold-color",
																"gk-sel-nylspan-ombre-088-kellygreen-color",
																"gk-sel-nylspan-ombre-116-navy-color",
																"gk-sel-nylspan-ombre-124-orange-color",
																"gk-sel-nylspan-ombre-139-pewter-color",
																"gk-sel-nylspan-ombre-148-purple-color",
																"gk-sel-nylspan-ombre-152-red-color",
																"gk-sel-nylspan-ombre-160-royal-color",
																"gk-sel-nylspan-ombre-165-sapphire-color",
																"gk-sel-nylspan-ombre-175-turquoise-color",
																"gk-sel-nylspan-ombre-180-white-color",
																"gk-sel-nylspan-ombre-192-sangria-color",
																"gk-sel-nylspan-ombre-338-electricblue-color",
																"gk-sel-nylspan-ombre-824-magenta-color",
																"gk-sel-nylspan-ombre-g27-calypso-color",
																"gk-sel-nylspan-ombre-v82-lipstick-color",
																"gk-sel-nylspan-ombre-v83-wysteria-color",
																"gk-sel-nylspan-ombre-016-black-color",
																"gk-sel-nylspan-ombre-y06-steel-color"],

																"gk-slg-submesh-palette"=>[
																	"gk-sel-submesh-y20-vegas-gold-color",
																	"gk-sel-submesh-y21-gold-color",
																	"gk-sel-submesh-y54-tangerine-color",
																	"gk-sel-submesh-y23-orange-color",
																	"gk-sel-submesh-y24-coral-color",
																	"gk-sel-submesh-y53-neon-yellow-color",
																	"gk-sel-submesh-y25-cosmos-color",
																	"gk-sel-submesh-y22-yellow-color",
																	"gk-sel-submesh-y29-crimson-color",
																	"gk-sel-submesh-y26-candy-apple-color",
																	"gk-sel-submesh-y28-red-color",
																	"gk-sel-submesh-y55-neon-pink-color",
																	"gk-sel-submesh-y61-berry-color",
																	"gk-sel-submesh-y31-pink-color",
																	"gk-sel-submesh-y62-hot-pink-color",
																	"gk-sel-submesh-y33-fuchsia-color",
																	"gk-sel-submesh-y32-cherry-color",
																	"gk-sel-submesh-y34-sangria-color",
																	"gk-sel-submesh-y35-wisteria-color",
																	"gk-sel-submesh-y36-purple-color",
																	"gk-sel-submesh-y56-ultra-violet-color",
																	"gk-sel-submesh-y63-wildberry-color",
																	"gk-sel-submesh-y37-navy-color",
																	"gk-sel-submesh-y38-sapphire-color",
																	"gk-sel-submesh-y39-midnight-color",
																	"gk-sel-submesh-y40-columbia-blue-color",
																	"gk-sel-submesh-y57-bright-turquoise-color",
																	"gk-sel-submesh-y42-royal-color",
																	"gk-sel-submesh-y44-turquoise-color",
																	"gk-sel-submesh-y43-electric-blue-color",
																	"gk-sel-submesh-y45-spruce-color",
																	"gk-sel-submesh-y46-evergreen-color",
																	"gk-sel-submesh-y58-key-lime-color",
																	"gk-sel-submesh-y47-kelly-green-color",
																	"gk-sel-submesh-y48-gray-color",
																	"gk-sel-submesh-y50-carbon-color",
																	"gk-sel-submesh-y49-flannel-gray-color",
																	"gk-sel-submesh-y51-black-color",
																	"gk-sel-submesh-y59-aluminum-color",
																	"gk-sel-submesh-y52-brown-color",
																	"gk-sel-submesh-y60-pewter-color",
																	"gk-sel-submesh-180-white-color",
																	"gk-sel-submesh-y03-teal-color",
																	"gk-sel-submesh-y04-blueribbon-color",
																	"gk-sel-submesh-y02-cardinal-color"], 

																	"gk-slg-submesh-ombre-none-palette" => [
																		"gk-sel-submesh-ombre-y21-gold-color",
																		"gk-sel-submesh-ombre-y54-tangerine-color",
																		"gk-sel-submesh-ombre-y20-vegas-gold-color",
																		"gk-sel-submesh-ombre-y23-orange-color",
																		"gk-sel-submesh-ombre-y22-yellow-color",
																		"gk-sel-submesh-ombre-y53-neon-yellow-color",
																		"gk-sel-submesh-ombre-y25-cosmo-color",
																		"gk-sel-submesh-ombre-y29-crimson-color",
																		"gk-sel-submesh-ombre-y55-neon-pink-color",
																		"gk-sel-submesh-ombre-y28-red-color",
																		"gk-sel-submesh-ombre-y24-coral-color",
																		"gk-sel-submesh-ombre-y26-candy-apple-color",
																		"gk-sel-submesh-ombre-y31-pink-color",
																		"gk-sel-submesh-ombre-y61-berry-color",
																		"gk-sel-submesh-ombre-y32-cherry-color",
																		"gk-sel-submesh-ombre-y62-hot-pink-color",
																		"gk-sel-submesh-ombre-y34-sangria-color",
																		"gk-sel-submesh-ombre-y33-fuchsia-color",
																		"gk-sel-submesh-ombre-y35-wisteria-color",
																		"gk-sel-submesh-ombre-y63-wildberry-color",
																		"gk-sel-submesh-ombre-y36-purple-color",
																		"gk-sel-submesh-ombre-y56-ultra-violet-color",
																		"gk-sel-submesh-ombre-y38-sapphire-color",
																		"gk-sel-submesh-ombre-y37-navy-color",
																		"gk-sel-submesh-ombre-y39-midnight-color",
																		"gk-sel-submesh-ombre-y57-bright-turquoise-color",
																		"gk-sel-submesh-ombre-y40-columbia-blue-color",
																		"gk-sel-submesh-ombre-y42-royal-color",
																		"gk-sel-submesh-ombre-y43-electric-blue-color",
																		"gk-sel-submesh-ombre-y45-spruce-color",
																		"gk-sel-submesh-ombre-y44-turquoise-color",
																		"gk-sel-submesh-ombre-y46-evergreen-color",
																		"gk-sel-submesh-ombre-y47-kelly-color",
																		"gk-sel-submesh-ombre-y58-key-lime-color",
																		"gk-sel-submesh-ombre-y48-gray-color",
																		"gk-sel-submesh-ombre-y50-carbon-color",
																		"gk-sel-submesh-ombre-y49-flannel-gray-color",
																		"gk-sel-submesh-ombre-y52-brown-color",
																		"gk-sel-submesh-ombre-y59-aluminum-color",
																		"gk-sel-submesh-ombre-y51-black-color",
																		"gk-sel-submesh-ombre-180-white-color",
																		"gk-sel-submesh-ombre-y60-pewter-color",
																		"gk-sel-submesh-ombre-y03-teal-color",
																		"gk-sel-submesh-ombre-y02-cardinal-color",
																		"gk-sel-submesh-ombre-y04-blue-ribbon-color"],

																		"gk-slg-mesh-ombre-palette" => [
																			"gk-sel-mesh-ombre-027-nude-color",
																			"gk-sel-mesh-ombre-015-berry-color",
																			"gk-sel-mesh-ombre-016-black-color",
																			"gk-sel-mesh-ombre-034-concord-color",
																			"gk-sel-mesh-ombre-121-ocean-color",
																			"gk-sel-mesh-ombre-180-white-color",
																			"gk-sel-mesh-ombre-q68-hotred-color",
																			"gk-sel-mesh-ombre-g27-calypso-color",
																			"gk-sel-mesh-ombre-w28-merlot-color",
																			"gk-sel-mesh-ombre-824-magenta-color",
																			"gk-sel-mesh-ombre-024-brown-color",
																			"gk-sel-mesh-ombre-116-navy-color"],

																			"gk-slg-nylpf-ombre-palette" => [
																				"gk-sel-nylspanfoil-ombre-f24-gold-mystique-color",
																				"gk-sel-nylspanfoil-ombre-752-columbiablue-mystique-color",
																				"gk-sel-nylspanfoil-ombre-902-ocean-mystique-color",
																				"gk-sel-nylspanfoil-ombre-24a-wildorchid-mystique-color",
																				"gk-sel-nylspanfoil-ombre-b81-red-mystique-color",
																				"gk-sel-nylspanfoil-ombre-d07-sunshine-mystique-color",
																				"gk-sel-nylspanfoil-ombre-d16-grape-mystique-color",
																				"gk-sel-nylspanfoil-ombre-d17-cherry-mystique-color",
																				"gk-sel-nylspanfoil-ombre-e16-navy-mystique-color",
																				"gk-sel-nylspanfoil-ombre-e59-blueraspberry-mystique-color",
																				"gk-sel-nylspanfoil-ombre-e84-silver-mystique-color",
																				"gk-sel-nylspanfoil-ombre-f21-berry-mystique-color",
																				"gk-sel-nylspanfoil-ombre-f22-black-mystique-color",
																				"gk-sel-nylspanfoil-ombre-f23-rainforest-mystique-color",
																				"gk-sel-nylspanfoil-ombre-f26-white-mystique-color",
																				"gk-sel-nylspanfoil-ombre-f87-electricturquoise-mystique-color",
																				"gk-sel-nylspanfoil-ombre-g83-lemonlime-mystique-color",
																				"gk-sel-nylspanfoil-ombre-h57-evergreen-mystique-color",
																				"gk-sel-nylspanfoil-ombre-h58-vinca-mystique-color",
																				"gk-sel-nylspanfoil-ombre-h63-lavenderice-mystique-color",
																				"gk-sel-nylspanfoil-ombre-h81-richroyal-mystique-color",
																				"gk-sel-nylspanfoil-ombre-j09-mintjulep-mystique-color",
																				"gk-sel-nylspanfoil-ombre-j46-plum-mystique-color",
																				"gk-sel-nylspanfoil-ombre-k91-lime-mystique-color",
																				"gk-sel-nylspanfoil-ombre-l23-gunmetal-mystique-color",
																				"gk-sel-nylspanfoil-ombre-l29-steel-mystique-color",
																				"gk-sel-nylspanfoil-ombre-l31-azure-mystique-color",
																				"gk-sel-nylspanfoil-ombre-l72-yellow-mystique-color",
																				"gk-sel-nylspanfoil-ombre-l93-charcoal-mystique-color",
																				"gk-sel-nylspanfoil-ombre-m37-merlot-mystique-color",
																				"gk-sel-nylspanfoil-ombre-n98-kellygreen-mystique-color",
																				"gk-sel-nylspanfoil-ombre-p30-sangria-mystique-color",
																				"gk-sel-nylspanfoil-ombre-q18-imperialpurple-mystique-color",
																				"gk-sel-nylspanfoil-ombre-u73-neonyellow-mystique-color",
																				"gk-sel-nylspanfoil-ombre-u78-neonlime-mystique-color",
																				"gk-sel-nylspanfoil-ombre-u79-neonpink-msytique-color",
																				"gk-sel-nylspanfoil-ombre-v04-passion-mystique-color",
																				"gk-sel-nylspanfoil-ombre-v05-sterlingsilver-mystique-color",
																				"gk-sel-nylspanfoil-ombre-x77-neoncoral-mystique-color",
																				"gk-sel-nylspanfoil-ombre-25a-peacock-iridescent-color",
																				"gk-sel-nylspanfoil-ombre-22a-champagne-mystique-color",
																				"gk-sel-nylspanfoil-ombre-51a-fluorescentlime-mystique-color",
																				"gk-sel-nylspanfoil-ombre-52a-fluorescentpink-mystique-color",
																				"gk-sel-nylspanfoil-ombre-53a-fluorescentorange-mystique-color",
																				"gk-sel-nylspanfoil-ombre-54a-fluorescentyellow-mystique-color",
																				"gk-sel-nylspanfoil-ombre-l24-gold-leaf-color"],

																				"gk-slg-holo-ombre-palette" => [
																					"gk-sel-holo-ombre-u74-grape-opalescence-color",
																					"gk-sel-holo-ombre-l35-black-sparkle-color",
																					"gk-sel-holo-ombre-799-white-sparkle-color",
																					"gk-sel-holo-ombre-j63-kelly-sparkle-color",
																					"gk-sel-holo-ombre-p28-radiantroyal-sparkle-color",
																					"gk-sel-holo-ombre-u06-fiesta-opalescence-color",
																					"gk-sel-holo-ombre-u07-jet-opalescence-color",
																					"gk-sel-holo-ombre-u08-fiesta-sparkle-color",
																					"gk-sel-holo-ombre-u71-magenta-sparkle-color",
																					"gk-sel-holo-ombre-u72-gold-opalescence-color",
																					"gk-sel-holo-ombre-u75-berry-opalescence-color",
																					"gk-sel-holo-ombre-u76-neongreen-opalescence-color",
																					"gk-sel-holo-ombre-u77-seaglass-opalescence-color",
																					"gk-sel-holo-ombre-u80-neonyellow-opalescence-color",
																					"gk-sel-holo-ombre-v02-white-opalescence-color",
																					"gk-sel-holo-ombre-v84-lemonlime-sparkle-color",
																					"gk-sel-holo-ombre-w64-turquoise-opalescence-color",
																					"gk-sel-holo-ombre-w65-magenta-opalescence-color",
																					"gk-sel-holo-ombre-w72-imperialpurple-sparkle-color",
																					"gk-sel-holo-ombre-23a-imperialpurple-opalescence-color",
																					"gk-sel-holo-ombre-w73-pacific-opalescence-color",
																					"gk-sel-holo-ombre-a75-seaglass-sparkle-color",
																					"gk-sel-holo-ombre-h36-turquoise-sparkle-color",
																					"gk-sel-holo-ombre-p27-wildsangria-sparkle-color",
																					"gk-sel-holo-ombre-p13-azure-sparkle-color"],

																					"gk-slg-holotek-ombre-palette" => [
																						"gk-sel-holotek-ombre-y20-vegas-gold-color",
																						"gk-sel-holotek-ombre-y21-gold-color",
																						"gk-sel-holotek-ombre-y22-yellow-color",
																						"gk-sel-holotek-ombre-y53-neon-yellow-color",
																						"gk-sel-holotek-ombre-y54-tangerine-color",
																						"gk-sel-holotek-ombre-y23-orange-color",
																						"gk-sel-holotek-ombre-y24-coral-color",
																						"gk-sel-holotek-ombre-y25-cosmo-color",
																						"gk-sel-holotek-ombre-y26-candy-apple-color",
																						"gk-sel-holotek-ombre-y28-red-color",
																						"gk-sel-holotek-ombre-y29-crimson-color",
																						"gk-sel-holotek-ombre-y55-neon-pink-color",
																						"gk-sel-holotek-ombre-y31-pink-color",
																						"gk-sel-holotek-ombre-y61-berry-color",
																						"gk-sel-holotek-ombre-y62-hot-pink-color",
																						"gk-sel-holotek-ombre-y32-cherry-color",
																						"gk-sel-holotek-ombre-y33-fuchsia-color",
																						"gk-sel-holotek-ombre-y34-sangria-color",
																						"gk-sel-holotek-ombre-y63-wildberry-color",
																						"gk-sel-holotek-ombre-y35-wisteria-color",
																						"gk-sel-holotek-ombre-y56-ultra-violet-color",
																						"gk-sel-holotek-ombre-y36-purple-color",
																						"gk-sel-holotek-ombre-y38-sapphire-color",
																						"gk-sel-holotek-ombre-y37-navy-color",
																						"gk-sel-holotek-ombre-y39-midnight-color",
																						"gk-sel-holotek-ombre-y40-columbia-blue-color",
																						"gk-sel-holotek-ombre-y57-bright-turquoise-color",
																						"gk-sel-holotek-ombre-y42-royal-color",
																						"gk-sel-holotek-ombre-y43-electric-blue-color",
																						"gk-sel-holotek-ombre-y44-turquoise-color",
																						"gk-sel-holotek-ombre-y45-spruce-color",
																						"gk-sel-holotek-ombre-y46-evergreen-color",
																						"gk-sel-holotek-ombre-y47-kelly-color",
																						"gk-sel-holotek-ombre-y58-key-lime-color",
																						"gk-sel-holotek-ombre-y48-gray-color",
																						"gk-sel-holotek-ombre-y49-flannel-gray-color",
																						"gk-sel-holotek-ombre-y50-carbon-color",
																						"gk-sel-holotek-ombre-y51-black-color",
																						"gk-sel-holotek-ombre-y52-brown-color",
																						"gk-sel-holotek-ombre-y59-aluminum-color",
																						"gk-sel-holotek-ombre-y60-pewter-color",
																						"gk-sel-holotek-ombre-180-white-color",
																						"gk-sel-holotek-ombre-y03-teal-color",
																						"gk-sel-holotek-ombre-y04-blue-ribbon-color",
																						"gk-sel-holotek-ombre-y02-cardinal-color"],

																						"gk-slg-sublimation-palette" => [
																							"gk-sel-sub-y39-midnight-color",
																							"gk-sel-sub-y40-columbiablue-color",
																							"gk-sel-sub-y57-brightturquoise-color",
																							"gk-sel-sub-y42-royal-color",
																							"gk-sel-sub-y43-electricblue-color",
																							"gk-sel-sub-y44-turquoise-color",
																							"gk-sel-sub-y45-spruce-color",
																							"gk-sel-sub-y46-evergreen-color",
																							"gk-sel-sub-y47-kellygreen-color",
																							"gk-sel-sub-y58-keylime-color",
																							"gk-sel-sub-y48-gray-color",
																							"gk-sel-sub-y51-black-color",
																							"gk-sel-sub-y52-brown-color",
																							"gk-sel-sub-y59-aluminum-color",
																							"gk-sel-sub-y60-pewter-color",
																							"gk-sel-sub-y62-hotpink-color",
																							"gk-sel-sub-y32-cherry-color",
																							"gk-sel-sub-y33-fuchsia-color",
																							"gk-sel-sub-y34-sangria-color",
																							"gk-sel-sub-y63-wildberry-color",
																							"gk-sel-sub-y35-wisteria-color",
																							"gk-sel-sub-y56-ultraviolet-color",
																							"gk-sel-sub-y36-purple-color",
																							"gk-sel-sub-y38-sapphire-color",
																							"gk-sel-sub-y37-navy-color",
																							"gk-sel-sub-y25-cosmos-color",
																							"gk-sel-sub-y26-candyapple-color",
																							"gk-sel-sub-y28-red-color",
																							"gk-sel-sub-y55-neonpink-color",
																							"gk-sel-sub-y31-pink-color",
																							"gk-sel-sub-y61-berry-color",
																							"gk-sel-sub-y54-tangerine-color",
																							"gk-sel-sub-y23-orange-color",
																							"gk-sel-sub-y24-coral-color",
																							"gk-sel-sub-y21-gold-color",
																							"gk-sel-sub-y22-yellow-color",
																							"gk-sel-sub-y53-neonyellow-color",
																							"gk-sel-sub-y20-vegasgold-color",
																							"gk-sel-sub-y29-crimson-color",
																							"gk-sel-sub-y49-grayflannel-color",
																							"gk-sel-sub-y50-carbon-color",
																							"gk-sel-sub-180-white-color",
																							"gk-sel-sub-y03-teal-color",
																							"gk-sel-sub-y04-blue-ribbon-color",
																							"gk-sel-sub-y02-cardinal-color"],

																							"gk-slg-polytek-ombre-palette" => [
																								"gk-sel-polytek-ombre-y20-vegas-gold-color",
																								"gk-sel-polytek-ombre-y21-gold-color",
																								"gk-sel-polytek-ombre-y22-yellow-color",
																								"gk-sel-polytek-ombre-y53-neon-yellow-color",
																								"gk-sel-polytek-ombre-y54-tangerine-color",
																								"gk-sel-polytek-ombre-y23-orange-color",
																								"gk-sel-polytek-ombre-y24-coral-color",
																								"gk-sel-polytek-ombre-y25-cosmo-color",
																								"gk-sel-polytek-ombre-y26-candy-apple-color",
																								"gk-sel-polytek-ombre-y28-red-color",
																								"gk-sel-polytek-ombre-y29-crimson-color",
																								"gk-sel-polytek-ombre-y55-neon-pink-color",
																								"gk-sel-polytek-ombre-y31-pink-color",
																								"gk-sel-polytek-ombre-y61-berry-color",
																								"gk-sel-polytek-ombre-y62-hot-pink-color",
																								"gk-sel-polytek-ombre-y32-cherry-color",
																								"gk-sel-polytek-ombre-y33-fuchsia-color",
																								"gk-sel-polytek-ombre-y34-sangria-color",
																								"gk-sel-polytek-ombre-y63-wildberry-color",
																								"gk-sel-polytek-ombre-y35-wisteria-color",
																								"gk-sel-polytek-ombre-y56-ultra-violet-color",
																								"gk-sel-polytek-ombre-y36-purple-color",
																								"gk-sel-polytek-ombre-y38-sapphire-color",
																								"gk-sel-polytek-ombre-y37-navy-color",
																								"gk-sel-polytek-ombre-y39-midnight-color",
																								"gk-sel-polytek-ombre-y40-columbia-blue-color",
																								"gk-sel-polytek-ombre-y57-bright-turquoise-color",
																								"gk-sel-polytek-ombre-y42-royal-color",
																								"gk-sel-polytek-ombre-y43-electric-blue-color",
																								"gk-sel-polytek-ombre-y44-turquoise-color",
																								"gk-sel-polytek-ombre-y45-spruce-color",
																								"gk-sel-polytek-ombre-y46-evergreen-color",
																								"gk-sel-polytek-ombre-y47-kelly-color",
																								"gk-sel-polytek-ombre-y58-key-lime-color",
																								"gk-sel-polytek-ombre-y48-gray-color",
																								"gk-sel-polytek-ombre-y49-flannel-gray-color",
																								"gk-sel-polytek-ombre-y50-carbon-color",
																								"gk-sel-polytek-ombre-y51-black-color",
																								"gk-sel-polytek-ombre-y52-brown-color",
																								"gk-sel-polytek-ombre-y59-aluminum-color",
																								"gk-sel-polytek-ombre-y60-pewter-color",
																								"gk-sel-polytek-ombre-180-white-color",
																								"gk-sel-polytek-ombre-y03-teal-color",
																								"gk-sel-polytek-ombre-y04-blue-ribbon-color",
																								"gk-sel-polytek-ombre-y02-cardinal-color"],

																								"gk-slg-subfuse-palette"=>[
																									"gk-sel-subfuse-y20-vegas-gold-color",
																									"gk-sel-subfuse-y23-orange-color",
																									"gk-sel-subfuse-y21-gold-color",
																									"gk-sel-subfuse-y53-neon-yellow-color",
																									"gk-sel-subfuse-y22-yellow-color",
																									"gk-sel-subfuse-y54-tangerine-color",
																									"gk-sel-subfuse-y24-coral-color",
																									"gk-sel-subfuse-y29-crimson-color",
																									"gk-sel-subfuse-y28-red-color",
																									"gk-sel-subfuse-y25-cosmos-color",
																									"gk-sel-subfuse-y55-neon-pink-color",
																									"gk-sel-subfuse-y26-candy-apple-color",
																									"gk-sel-subfuse-y31-pink-color",
																									"gk-sel-subfuse-y61-berry-color",
																									"gk-sel-subfuse-y62-hot-pink-color",
																									"gk-sel-subfuse-y32-cherry-color",
																									"gk-sel-subfuse-y34-sangria-color",
																									"gk-sel-subfuse-y33-fuchsia-color",
																									"gk-sel-subfuse-y63-wildberry-color",
																									"gk-sel-subfuse-y35-wisteria-color",
																									"gk-sel-subfuse-y56-ultra-violet-color",
																									"gk-sel-subfuse-y36-purple-color",
																									"gk-sel-subfuse-y38-sapphire-color",
																									"gk-sel-subfuse-y37-navy-color",
																									"gk-sel-subfuse-y39-midnight-color",
																									"gk-sel-subfuse-y40-columbia-blue-color",
																									"gk-sel-subfuse-y42-royal-color",
																									"gk-sel-subfuse-y57-bright-turquoise-color",
																									"gk-sel-subfuse-y43-electric-blue-color",
																									"gk-sel-subfuse-y44-turquoise-color",
																									"gk-sel-subfuse-y46-evergreen-color",
																									"gk-sel-subfuse-y45-spruce-color",
																									"gk-sel-subfuse-y47-kelly-green-color",
																									"gk-sel-subfuse-y58-key-lime-color",
																									"gk-sel-subfuse-y48-gray-color",
																									"gk-sel-subfuse-y49-flannel-gray-color",
																									"gk-sel-subfuse-y50-carbon-color",
																									"gk-sel-subfuse-y51-black-color",
																									"gk-sel-subfuse-y52-brown-color",
																									"gk-sel-subfuse-y60-pewter-color",
																									"gk-sel-subfuse-y59-aluminum-color",
																									"gk-sel-subfuse-180-white-color",
																									"gk-sel-subfuse-y03-teal-color",
																									"gk-sel-subfuse-y04-blueribbon-color",
																									"gk-sel-subfuse-y02-cardinal-color"],

																									"gk-slg-holotek-palette" => [
																										"gk-sel-holotek-y20-vegas-gold-color",
																										"gk-sel-holotek-y23-orange-color",
																										"gk-sel-holotek-y21-gold-color",
																										"gk-sel-holotek-y53-neon-yellow-color",
																										"gk-sel-holotek-y22-yellow-color",
																										"gk-sel-holotek-y54-tangerine-color",
																										"gk-sel-holotek-y24-coral-color",
																										"gk-sel-holotek-y29-crimson-color",
																										"gk-sel-holotek-y28-red-color",
																										"gk-sel-holotek-y55-neon-pink-color",
																										"gk-sel-holotek-y26-candy-apple-color",
																										"gk-sel-holotek-y31-pink-color",
																										"gk-sel-holotek-y61-berry-color",
																										"gk-sel-holotek-y62-hot-pink-color",
																										"gk-sel-holotek-y32-cherry-color",
																										"gk-sel-holotek-y34-sangria-color",
																										"gk-sel-holotek-y33-fuchsia-color",
																										"gk-sel-holotek-y63-wildberry-color",
																										"gk-sel-holotek-y35-wisteria-color",
																										"gk-sel-holotek-y56-ultra-violet-color",
																										"gk-sel-holotek-y36-purple-color",
																										"gk-sel-holotek-y38-sapphire-color",
																										"gk-sel-holotek-y37-navy-color",
																										"gk-sel-holotek-y39-midnight-color",
																										"gk-sel-holotek-y40-columbia-blue-color",
																										"gk-sel-holotek-y42-royal-color",
																										"gk-sel-holotek-y57-bright-turquoise-color",
																										"gk-sel-holotek-y43-electric-blue-color",
																										"gk-sel-holotek-y44-turquoise-color",
																										"gk-sel-holotek-y46-evergreen-color",
																										"gk-sel-holotek-y45-spruce-color",
																										"gk-sel-holotek-y58-key-lime-color",
																										"gk-sel-holotek-y48-gray-color",
																										"gk-sel-holotek-y49-flannel-gray-color",
																										"gk-sel-holotek-y50-carbon-color",
																										"gk-sel-holotek-y51-black-color",
																										"gk-sel-holotek-y52-brown-color",
																										"gk-sel-holotek-y60-pewter-color",
																										"gk-sel-holotek-y59-aluminum-color",
																										"gk-sel-holotek-180-white-color",
																										"gk-sel-holotek-y03-teal-color",
																										"gk-sel-holotek-y02-cardinal-color",
																										"gk-sel-holotek-y25-cosmo-color",
																										"gk-sel-holotek-y04-blueribbon-color",
																										"gk-sel-holotek-y47-kelly-green-color"],

																										"gk-slg-holotek-ombre-none-palette" => [
																											"gk-sel-holotek-ombre-y20-vegas-gold-color",
																											"gk-sel-holotek-ombre-y22-yellow-color",
																											"gk-sel-holotek-ombre-y25-cosmo-color",
																											"gk-sel-holotek-ombre-y54-tangerine-color",
																											"gk-sel-holotek-ombre-y53-neon-yellow-color",
																											"gk-sel-holotek-ombre-y24-coral-color",
																											"gk-sel-holotek-ombre-y23-orange-color",
																											"gk-sel-holotek-ombre-y26-candy-apple-color",
																											"gk-sel-holotek-ombre-y55-neon-pink-color",
																											"gk-sel-holotek-ombre-y28-red-color",
																											"gk-sel-holotek-ombre-y31-pink-color",
																											"gk-sel-holotek-ombre-y61-berry-color",
																											"gk-sel-holotek-ombre-y62-hot-pink-color",
																											"gk-sel-holotek-ombre-y32-cherry-color",
																											"gk-sel-holotek-ombre-y33-fuchsia-color",
																											"gk-sel-holotek-ombre-y34-sangria-color",
																											"gk-sel-holotek-ombre-y63-wildberry-color",
																											"gk-sel-holotek-ombre-y35-wisteria-color",
																											"gk-sel-holotek-ombre-y56-ultra-violet-color",
																											"gk-sel-holotek-ombre-y36-purple-color",
																											"gk-sel-holotek-ombre-y38-sapphire-color",
																											"gk-sel-holotek-ombre-y37-navy-color",
																											"gk-sel-holotek-ombre-y21-gold-color",
																											"gk-sel-holotek-ombre-y39-midnight-color",
																											"gk-sel-holotek-ombre-y57-bright-turquoise-color",
																											"gk-sel-holotek-ombre-y29-crimson-color",
																											"gk-sel-holotek-ombre-y40-columbia-blue-color",
																											"gk-sel-holotek-ombre-y43-electric-blue-color",
																											"gk-sel-holotek-ombre-y42-royal-color",
																											"gk-sel-holotek-ombre-y44-turquoise-color",
																											"gk-sel-holotek-ombre-y45-spruce-color",
																											"gk-sel-holotek-ombre-y46-evergreen-color",
																											"gk-sel-holotek-ombre-y47-kelly-color",
																											"gk-sel-holotek-ombre-y48-gray-color",
																											"gk-sel-holotek-ombre-y58-key-lime-color",
																											"gk-sel-holotek-ombre-y49-flannel-gray-color",
																											"gk-sel-holotek-ombre-y51-black-color",
																											"gk-sel-holotek-ombre-y52-brown-color",
																											"gk-sel-holotek-ombre-y50-carbon-color",
																											"gk-sel-holotek-ombre-y59-aluminum-color",
																											"gk-sel-holotek-ombre-y60-pewter-color",
																											"gk-sel-holotek-ombre-y04-blue-ribbon-color",
																											"gk-sel-holotek-ombre-y03-teal-color",
																											"gk-sel-holotek-ombre-y02-cardinal-color",
																											"gk-sel-holotek-ombre-180-white-color"],

																											"gk-slg-spanglez-palette" => [
																												"gk-sel-spanglez-n42-silverglossy-color",
																												"gk-sel-spanglez-n41-goldglossy-color",
																												"gk-sel-spanglez-015-berryglossy-color",
																												"gk-sel-spanglez-016-blackglossy-color",
																												"gk-sel-spanglez-088-kellygreen-glossy-color",
																												"gk-sel-spanglez-124-orange-glossy-color",
																												"gk-sel-spanglez-148-purpleglossy-color",
																												"gk-sel-spanglez-152-redflat-color",
																												"gk-sel-spanglez-160-royalflat-color",
																												"gk-sel-spanglez-175-turqglossy-color",
																												"gk-sel-spanglez-191-seaglass-glossy-color",
																												"gk-sel-spanglez-p48-lemonlimeflat-color",
																												"gk-sel-spanglez-p49-silverholo-color",
																												"gk-sel-spanglez-p50-goldholo-color",
																												"gk-sel-spanglez-p51-berryholo-color",
																												"gk-sel-spanglez-p53-redholo-color",
																												"gk-sel-spanglez-p54-royalholo-color",
																												"gk-sel-spanglez-p55-kellygreenholo-color",
																												"gk-sel-spanglez-p57-lemonlimeholo-color",
																												"gk-sel-spanglez-140-pinkglossy-color"],

																												"gk-slg-sequinz-palette" => [
																													"gk-sel-sequinz-180-white-color",
																													"gk-sel-sequinz-n42-silver-color",
																													"gk-sel-sequinz-p49-silver-hologram-color",
																													"gk-sel-sequinz-016-black-color",
																													"gk-sel-sequinz-152-red-color",
																													"gk-sel-sequinz-p53-red-hologram-color",
																													"gk-sel-sequinz-n41-gold-color",
																													"gk-sel-sequinz-p50-gold-hologram-color",
																													"gk-sel-sequinz-p48-lemonlime-color",
																													"gk-sel-sequinz-p57-lemonlime-hologram-color",
																													"gk-sel-sequinz-088-kellygreen-color",
																													"gk-sel-sequinz-p55-kellygreen-hologram-color",
																													"gk-sel-sequinz-175-turquoise-color",
																													"gk-sel-sequinz-p58-turquoise-hologram-color",
																													"gk-sel-sequinz-160-royal-color",
																													"gk-sel-sequinz-p54-royal-hologram-color",
																													"gk-sel-sequinz-148-purple-color",
																													"gk-sel-sequinz-015-berry-color",
																													"gk-sel-sequinz-p51-berry-hologram-color",
																													"gk-sel-sequinz-140-pink-color",
																													"gk-sel-sequinz-p52-pink-hologram-color",
																													"gk-sel-sequinz-124-orange-color",
																													"gk-sel-sequinz-v58-orange-hologram-color"]}

																													$gk_svg_urls = [
																														"https://www.gkelite.com/apps/storage/images/project/style/1678.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1680.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1700m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1774.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1786.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1787.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1811m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1812m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1813m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1817m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1818m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1832m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1845m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1846m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1853st.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1882m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1883m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1884m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/1885m.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/2011.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/2012.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3456.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3457.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3619.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3718.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3744.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3772.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3773.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3775.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3776.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3777.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3779.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3801.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3802.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3803.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3804.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3807.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3811.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3813.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3814.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3815.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3816.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3817.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3818.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3819.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/3820.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/5841st.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/5844st.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/5846st.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/5847st.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/5848st.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/5849st.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/5850st.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/5851st.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/5852st.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/6320.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/6331.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/6334.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/e2071.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/e2259.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/e3674.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/e3677.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/e3678.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/e3679.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/e3680.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/e3681.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/e3682.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/e3683.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/e3684.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/l1037.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/l1048.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/l1051.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/swu02.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/swu06.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/swu09.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/swu10.svg",
																														"https://www.gkelite.com/apps/storage/images/project/style/swu11.svg"]


																														$gk_products = ["8788","8731","8787","8253","8252","2008","4854","4875","4882","4885","4883","4888s","4892s","4893s","4894s","4895","4896s","7551","7557","7560","7561","7562","7567","7578","7585","7593","7596","7597","7598","7599","7600","7601","7603","7604","7605","7606","7607","7608","7609","7610","7611s","7613s","7616s","7617","7618","7619","7620","7621","7622","7623","7624","7625","7626","7627","7628","7629","7630","7631","9541","9585","9587","9591","9599","9600","9601","9602","9603","9604","9605","9608","9609","9610","9611","9612","9613","9614","9615s","9616","9617","9618","9619","9620","8777","9594","wl355","wl371","wl374","wl381","wl382","wl389","wl397","wl440","wl428","1103s","1817","1853","1873","1933","1939","1946","1954","1960","1964","1966","1974s","1101s","1102s","1104s","1105s","1106s","1108s","1107s","1109s","1110s","1112","1113","1965","1111","1846","1818","6108","6109","6110","6111","6112","6113","6114","6115","6502","6506","6508","6710","6711","6713","6714","6501","6503","6701","6712s","6509s","6104","6116","6626","6654","6655","6656","6628","6627","4885S","7560S","7562S","7578S","7597S","7600S","7601S","7603S","7604S","7605S","7606S","7607S","7609S","7621S","7622S"]

																													end